### ISSUE TITLE
Необходимы исправления

### ISSUE THREAD

**Issue by seleckis** [Polupanova/MOOD#1]
Прибрать файлы:
1. .css файл должн быть перенесен в папку css
2. photo-01.jpg из корня убрать
3. У главного html файла должено быть название index.html

CSS:
1. Не пишем значение auto, 100% или 0, если оно и так по умолчанию или ни на что не влияет. Нужно все проверить. 
2. Не повторяем слишком часто свойства (например `font-size`, `font-family`, `color`) если можно один раз написать это свойство для элемента более высокого по иерархии.
3. Не пишем свойства для всех тегов (например `ul`, `iframe`), которые радикально меняют внешний вид. Например, у вас прописан `padding-right` для всех `<ul>`, это плохо, поскольку влияет на все списки. Но, например, `img{  border: none; }` годится, потому, что убирает рамку в IE, если картинка в ссылке.
4. `float: right` подразумевает `display: block`, поэтому нет смысла писать, свойство `display` в этом случае.
5. Лучше делать внутренний отступ у родителя, чем внешний у дочернего элемента
6. Можно просто написать `right: 50px`:

``` css
.navigator-dots {
    margin-right: 50px;
    right: 0;
}
```
1. Нужно оптимизировать назвав одинаковыми классами все однообразные элементы (например заголовки для каждой секции)
2. По возможности не прописывайте высоту блоков, если содержимое может быть больше (например `.one-offer-block`).

HTML: 
1. `<div class="imgsocial"><li>` — теги `<li>` можно писать только внутри `<ul>` или `<ol>`
2. `<div class="title-offers">` — для заголовков лучше использовать стандартные теги `<h1>`, `<h2>` и т.д.
3. Как я говорил на занятии с названиями классов нужно поработать.
4. `<div class "brush">` — не хватает =
5. Для многострочного текста нужны `<p>`. Без использования `<br>`
6. Ссылки `.work-dots` должны быть кнопками.
7. Пропал закрывающий тег у `<div class="picture-txt">` 
8. `<tfoot>` лучше перенести после `<tbody>`
9. У таких кодов как `&#8364` в конце нужно писать `;`, т.е. `&#8364;`. А вообще этот символ можно написать с помощью кода `&euro;` или просто вставить символ `€`.
10. Ссылку в `<div class="team-picture">` не нужно, она все равно не работает
11. Лишний тег `<form>` внутри `<form action="URL">`. И не пишите URL, поставьте `#`. Но там будет какой-то адрес.
12. Лучше помещать каждый `<input>`, `<textarea>`, `<button>` в какой-то контейнер.
13. В конце `<div class="class">` тоже какое-то безликое название класса.
14. `conteiner` пишется `container`, `adress` пишется `address`.

Когда исправите, будет код почище, я еще раз посмотрю.

**Comment by Polupanova** [comment]
спасибо огромное.обязательно все исправлю :)
